version: '3.6'

networks:
  service_bridge:
    external: true

services:
  training_ui:
    image: 'httpd:2.4'
    container_name: 'training_ui'
    volumes:
      - ui_files:/usr/local/apache2/htdocs/training/ 
    ports:
      - '5021:80'
    networks:
      - service_bridge
    restart: on-failure:3

volumes:
  ui_files:
    driver: local
    name: ui_files
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/algonox/Desktop/Akhil/ACE/microservices/training_ui/BL/training'
