version: '3.6'

networks:
  service_bridge:
    name: service_bridge
    driver: overlay

services:
  # Reports
  reports_consumer:
    image: 'reports_consumer'
    container_name: 'reports_consumer'
    build:
      context: ./reports_api/BL/app
      dockerfile: generate_report.Dockerfile
    networks:
      - service_bridge
    restart: on-failure:3
    environment:
      - HOST_IP=${HOST_IP}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_FORMAT=${LOG_FORMAT}
      - LOCAL_DB_PASSWORD=${LOCAL_DB_PASSWORD}
    volumes:
      - reports_output:/app/reports
    # logging:
    #   driver: gelf
    #   options:
    #     gelf-address: udp://127.0.0.1:12201
    #     tag: "table_merger_tag"
        
  # Digital Signature
  digital_signature:
    image: 'digital_signature'
    container_name: 'digital_signature'
    build: ./digital_signature_api/BL
    networks:
      - service_bridge
    restart: on-failure:3
    environment:
      - HOST_IP=${HOST_IP}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_FORMAT=${LOG_FORMAT}
      - LOCAL_DB_PASSWORD=${LOCAL_DB_PASSWORD}
    volumes:
      - files:/app/files
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:12201
        tag: "table_merger_tag"

  # Template Detection
  detection_app:
    image: 'detection_app'
    container_name: 'detection_app'
    build: ./template_detection/BL
    networks:
      - service_bridge
    volumes:
      - detection_input:/app/input
      - angular:/app/angular
      - training_images:/app/training_ui
    restart: on-failure:3
    environment:
      - HOST_IP=${HOST_IP}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_FORMAT=${LOG_FORMAT}
      - LOCAL_DB_PASSWORD=${LOCAL_DB_PASSWORD}
    # logging:
    #   driver: gelf
    #   options:
    #     gelf-address: udp://127.0.0.1:12201
    #     tag: "table_merger_tag"

  # Extraction
  extraction:
    image: 'extraction'
    container_name: 'extraction'
    build:
      context: ./extraction_api/BL/app
      dockerfile: consumer.Dockerfile
    networks:
      - service_bridge
    restart: on-failure:3
    environment:
      - HOST_IP=${HOST_IP}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_FORMAT=${LOG_FORMAT}
      - LOCAL_DB_PASSWORD=${LOCAL_DB_PASSWORD}
    volumes:
      - invoice_files:/app/invoice_files
    # logging:
    #   driver: gelf
    #   options:
    #     gelf-address: udp://127.0.0.1:12201
    #     tag: "table_merger_tag"

  # Table Extraction
  table_api:
    image: 'table_api'
    container_name: 'table_api'
    build:
      context: ./table_api/BL
      dockerfile: api.Dockerfile
    networks:
      service_bridge:
        aliases:
          - tableapi
    restart: on-failure:3
    environment:
      - HOST_IP=${HOST_IP}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_FORMAT=${LOG_FORMAT}
      - LOCAL_DB_PASSWORD=${LOCAL_DB_PASSWORD}
    volumes:
      - invoice_files:/var/www/table_api/app/invoice_files
    # logging:
    #   driver: gelf
    #   options:
    #     gelf-address: udp://127.0.0.1:12201
    #     tag: "table_merger_tag"

  table_consumer:
    image: 'table_consumer'
    container_name: 'table_consumer'
    build:
      context: ./table_api/BL/app
      dockerfile: consumer.Dockerfile
    networks:
      - service_bridge
    restart: on-failure:3
    environment:
      - HOST_IP=${HOST_IP}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_FORMAT=${LOG_FORMAT}
      - LOCAL_DB_PASSWORD=${LOCAL_DB_PASSWORD}
    volumes:
      - invoice_files:/app/invoice_files
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:12201
        tag: "table_merger_tag"

  business_rules_consumer:
    image: 'business_rules_consumer'
    container_name: 'business_rules_consumer'
    build:
      context: ./business_rules_api/BL/app
      dockerfile: consumer.Dockerfile
    networks:
      - service_bridge
    restart: on-failure:3
    environment:
      - HOST_IP=${HOST_IP}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_FORMAT=${LOG_FORMAT}
      - LOCAL_DB_PASSWORD=${LOCAL_DB_PASSWORD}
    # logging:
    #   driver: gelf
    #   options:
    #     gelf-address: udp://127.0.0.1:12201
    #     tag: "table_merger_tag"
  
  # JSON Export
  json_export_api:
    image: 'json_export_api'
    container_name: 'json_export_api'
    build: ./json_export_api/BL
    networks:
      service_bridge:
        aliases:
          - jsonexportapi
    volumes:
      - json_output:/app/output
    restart: on-failure:3
    environment:
      - HOST_IP=${HOST_IP}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_FORMAT=${LOG_FORMAT}
      - LOCAL_DB_PASSWORD=${LOCAL_DB_PASSWORD}
    depends_on: 
      - json_export_db
      - json_export_php
    # logging:
    #   driver: gelf
    #   options:
    #     gelf-address: udp://127.0.0.1:12201
    #     tag: "table_merger_tag"

  # Table Merger
  table_merger_consumer:
    image: 'table_merger_consumer'
    container_name: 'table_merger_consumer'
    build:
      context: ./table_merger_api/BL/app
      dockerfile: consumer.Dockerfile
    networks:
      - service_bridge
    restart: on-failure:3
    environment:
      - HOST_IP=${HOST_IP}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_FORMAT=${LOG_FORMAT}
      - LOCAL_DB_PASSWORD=${LOCAL_DB_PASSWORD}
    # logging:
    #   driver: gelf
    #   options:
    #     gelf-address: udp://127.0.0.1:12201
    #     tag: "table_merger_tag"

  # Save Changes
  save_changes:
    image: 'save_changes'
    container_name: 'save_changes'
    build:
      context: ./queue_api/BL/app
      dockerfile: save_changes.Dockerfile
    networks:
      - service_bridge
    restart: on-failure:3
    environment:
      - HOST_IP=${HOST_IP}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_FORMAT=${LOG_FORMAT}
      - LOCAL_DB_PASSWORD=${LOCAL_DB_PASSWORD}
    # logging:
    #   driver: gelf
    #   options:
    #     gelf-address: udp://127.0.0.1:12201
    #     tag: "table_merger_tag"

  # Update Queue
  update_queue:
    image: 'update_queue'
    container_name: 'update_queue'
    build:
      context: ./queue_api/BL/app
      dockerfile: update_queue.Dockerfile
    networks:
      - service_bridge
    restart: on-failure:3
    environment:
      - HOST_IP=${HOST_IP}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_FORMAT=${LOG_FORMAT}
      - LOCAL_DB_PASSWORD=${LOCAL_DB_PASSWORD}
    # logging:
    #   driver: gelf
    #   options:
    #     gelf-address: udp://127.0.0.1:12201
    #     tag: "table_merger_tag"

  # Case Creation
  case_creation:
    image: 'case_creation'
    container_name: 'case_creation'
    build:
      context: ./queue_api/BL/app
      dockerfile: case_creation.Dockerfile
    networks:
      - service_bridge
    restart: on-failure:3
    environment:
      - HOST_IP=${HOST_IP}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_FORMAT=${LOG_FORMAT}
      - LOCAL_DB_PASSWORD=${LOCAL_DB_PASSWORD}
    volumes:
      - case_creation:/app/case_creation
    # logging:
    #   driver: gelf
    #   options:
    #     gelf-address: udp://127.0.0.1:12201
    #     tag: "table_merger_tag"

  # Run Business Rules
  run_business_rule:
    image: 'run_business_rule'
    container_name: 'run_business_rule'
    build:
      context: ./business_rules_api/BL/app
      dockerfile: run_business_rule.Dockerfile
    networks:
      - service_bridge
    restart: on-failure:3
    environment:
      - HOST_IP=${HOST_IP}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_FORMAT=${LOG_FORMAT}
      - LOCAL_DB_PASSWORD=${LOCAL_DB_PASSWORD}
    # logging:
    #   driver: gelf
    #   options:
    #     gelf-address: udp://127.0.0.1:12201
    #     tag: "table_merger_tag"
  
  # Process Time
  process_time:
    image: 'process_time'
    container_name: 'process_time'
    build: ./process_time/BL
    networks:
      - service_bridge
    restart: on-failure:3
    environment:
      - HOST_IP=${HOST_IP}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_FORMAT=${LOG_FORMAT}
      - LOCAL_DB_PASSWORD=${LOCAL_DB_PASSWORD}
    # logging:
    #   driver: gelf
    #   options:
    #     gelf-address: udp://127.0.0.1:12201
    #     tag: "process_time_tag"

  # Update Addon Table
  update_addon:
    image: 'update_addon'
    container_name: 'update_addon'
    build:
      context: ./queue_api/BL/app
      dockerfile: update_addon.Dockerfile
    networks:
      - service_bridge
    restart: on-failure:3
    environment:
      - HOST_IP=${HOST_IP}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_FORMAT=${LOG_FORMAT}
      - LOCAL_DB_PASSWORD=${LOCAL_DB_PASSWORD}
    # logging:
    #   driver: gelf
    #   options:
    #     gelf-address: udp://127.0.0.1:12201
    #     tag: "update_addon_tag"

volumes:
  # Reports
  reports_output:
    driver: local
    name: reports_output
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${REPORT_OUTPUT_PATH}

  # JSON Export
  json_output:
    driver: local
    name: json_output
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${JSON_EXPORT_PATH}

  # Case Creation
  case_creation:
    driver: local
    name: case_creation
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${XAMPP_PATH}/htdocs/
      
  # Digital Signature and ACE Template Training
  files:
    external: true
    name: file_output

  # Template Detection
  detection_input:
    external: true
    name: file_output

  angular:
    external: true
    name: angular_images

  training_images:
    external: true
    name: ui_images

  # Table API
  invoice_files:
    external: true
    name: file_output