version: '3.6'

networks:
  service_bridge:
    name: service_bridge
    driver: overlay

services:
  # Approve button function
  karvy_approve:
    image: 'karvy_approve'
    container_name: 'karvy_approve'
    build:
      context: ./karvy_services/button_functions/BL/
      dockerfile: approve_recon.Dockerfile
    networks:
      - service_bridge
    restart: on-failure:3
    environment:
      - HOST_IP=${HOST_IP}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_FORMAT=${LOG_FORMAT}
      - LOCAL_DB_PASSWORD=${LOCAL_DB_PASSWORD}
    # logging:
    #   driver: gelf
    #   options:
    #     gelf-address: udp://127.0.0.1:12201
    #     tag: "karvy_approve_tag"
  
  # Reject button function
  karvy_reject:
    image: 'karvy_reject'
    container_name: 'karvy_reject'
    build:
      context: ./karvy_services/button_functions/BL/
      dockerfile: reject_recon.Dockerfile
    networks:
      - service_bridge
    restart: on-failure:3
    environment:
      - HOST_IP=${HOST_IP}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_FORMAT=${LOG_FORMAT}
      - LOCAL_DB_PASSWORD=${LOCAL_DB_PASSWORD}
    # logging:
    #   driver: gelf
    #   options:
    #     gelf-address: udp://127.0.0.1:12201
    #     tag: "karvy_reject_tag"
    
  # Stats 
  karvy_stats:
    image: 'karvy_stats'
    container_name: 'karvy_stats'
    build: ./karvy_services/stats_api/BL/
    networks:
      service_bridge:
        aliases:
          - karvystats
    restart: on-failure:3
    environment:
      - HOST_IP=${HOST_IP}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_FORMAT=${LOG_FORMAT}
      - LOCAL_DB_PASSWORD=${LOCAL_DB_PASSWORD}
    # logging:
    #   driver: gelf
    #   options:
    #     gelf-address: udp://127.0.0.1:12201
    #     tag: "karvy_stats_tag"
  
  # Stats 
  karvy_email:
    image: 'karvy_email_trigger'
    container_name: 'karvy_email_trigger'
    build: ./karvy_services/stats_api_email/BL/
    networks:
      service_bridge:
        aliases:
          - karvyemailtrigger
    restart: on-failure:3
    environment:
      - HOST_IP=${HOST_IP}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_FORMAT=${LOG_FORMAT}
      - LOCAL_DB_PASSWORD=${LOCAL_DB_PASSWORD}
    # logging:
    #   driver: gelf
    #   options:
    #     gelf-address: udp://127.0.0.1:12201
    #     tag: "karvy_email_trigger_tag"