version: '3.6'

networks:
  service_bridge:
    external: true

services:
  common_db:
    image: mysql:5.7
    container_name: 'common_db'
    ports:
      - '32001:3306'
    volumes:
      - ./:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWROD}
    networks:
      - service_bridge
    restart: on-failure:3
