version: '3.6'

networks:
  service_bridge:
    external: true

services:
  detection_app:
    image: 'detection_app'
    container_name: 'detection_app'
    build: ./BL
    networks:
      - service_bridge
    volumes:
      - detection_input:/app/input
    restart: on-failure:3

  template_db:
    image: mysql:5.7
    container_name: 'template_db'
    ports:
      - '32000:3306'
    volumes:
      - ./DL:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWROD}
    networks:
      - service_bridge
    restart: on-failure:3

volumes:
  detection_input:
    external: true
    name: file_output