version: '3.6'

networks:
  service_bridge:
    external: true

services:
  export_excel:
    image: 'export_excel'
    container_name: 'export_excel'
    build: ./BL
    ports:
      - '5003:5000'
    networks:
      - service_bridge
    restart: on-failure:3
    volumes:
      - excel_output:/app/output

volumes:
  # Excel Export Output
  excel_output:
    driver: local
    name: excel_output
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/ashyamzubair/Documents/Sprint Tasks/excel_export_api/BL/output'