version: '3.6'

networks:
  service_bridge:
    external: true

services:
  export_excel:
    image: 'json_export'
    container_name: 'json_export'
    build: ./BL
    ports:
      - '5003:5000'
    networks:
      - service_bridge
    restart: on-failure:3
    volumes:
      - json_output:/app/output

volumes:
  # JSON Export Output
  json_output:
    driver: local
    name: json_output
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/ashyamzubair/Documents/Sprint Tasks/json_export_api/BL/output'