version: '3.6'

services:
  service_bridge_apache:
    image: service_bridge_apache
    container_name: service_bridge_apache
    build: .
    ports:
      - '5050:80'
    restart: on-failure:3


  

