version: '3.6'

networks:
  service_bridge:
    external: true

services:
  pdf_plumber_api:
    image: 'pdf_plumber_api'
    container_name: 'pdf_plumber_api'
    build: ./BL
    ports:
      - '5022:5000'
    networks:
      - service_bridge
    restart: on-failure:3
    volumes:
      - invoice_files:/app/invoice_files

volumes:
  invoice_files:
    external: true
    name: file_output