version: '3.6'

networks:
  service_bridge:
    external: true

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: 'zookeeper'
    networks:
      - service_bridge
    ports:
      - '2181:2181'
    restart: on-failure:3
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  broker:
    image: 'bitnami/kafka:latest'
    container_name: 'broker'
    networks:
      - service_bridge
    restart: on-failure:3
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=1

  producer:
    image: 'producer'
    container_name: 'producer'
    build: ./producer
    ports:
      - '6969:6969'
    networks:
      - service_bridge
    restart: on-failure:3

  consumer:
    image: 'consumer'
    container_name: 'consumer'
    build: ./consumer
    ports:
      - '6968:6968'
    networks:
      - service_bridge
    restart: on-failure:3