version: '3.6'

networks:
  service_bridge:
    external: true

services:
  folder_monitor:
    image: 'folder_monitor'
    container_name: 'folder_monitor'
    build: ./BL
    ports:
      - '5007:5007'
    volumes:
      - file_input:/app/PortalTest
      - file_output:/app/output
      - ui_path:/app/output
    networks:
      - service_bridge
    restart: on-failure:3

volumes:
  file_input:
    driver: local
    name: file_input
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'c//Users/t00004100/Desktop/ashyam/PortalTest'
  file_output:
    driver: local
    name: file_output
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'c//Users/t00004100/Desktop/ashyam/output'
